package cn.lhzs.data.dao;

import cn.lhzs.data.bean.Article;
import tk.mybatis.mapper.common.Mapper;

public interface ArticleMapper extends Mapper<Article> {
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    int insert(Article record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    int insertSelective(Article record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    Article selectByPrimaryKey(Long id);
//
//    List<Article> selectListByType(Article type);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(Article record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table article
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(Article record);
//
//    /**
//     * 查询文章总数
//     * @return
//     */
//    Integer selectCount(Map map);
}