package cn.lhzs.data.dao;

import cn.lhzs.data.bean.Meta;
import org.springframework.stereotype.Repository;

@Repository
public interface MetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    int insert(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    int insertSelective(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    Meta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Meta record);
}