package cn.lhzs.data.dao;

import cn.lhzs.data.bean.Product;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * 批量插入
     *
     * @mbggenerated
     */
    int batchInsert(List<Product> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Long prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    /**
     * 获取商品列表
     * @param product 商品对象
     * @return 商品列表
     */
    List<Product> selectProduct(Product product);

    /**
     * 搜索关键字
     * @param map 参数对象
     * @return 商品列表
     */
    List<Product> searchProduct(Map map);

    /**
     * 统计总数
     * @param map
     * @return
     */
    Long selectCount(Map map);

    /**
     * 删除数据库表所有数据
     */
    void deleteTable();

    /**
     * 定时删除过期商品
     */
    void timerDeleteTask(String expiration);
}