package cn.lhzs.data.dao;

import cn.lhzs.data.bean.Shop;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    Shop selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shop record);

    /**
     * 获取商店列表
     * @param shop 商店对象
     * @return 商店列表
     */
    List<Shop> selectShop(Shop shop);

    /**
     * 搜索商店
     * @param map 参数对象
     * @return 店铺列表
     */
    List<Shop> searchShop(Map map);

    /**
     * 根据类型获取店铺
     * @param shop 店铺对象
     * @return 总个数
     */
    Integer selectCountByType(Shop shop);
}