package cn.lhzs.data.bean;

import java.util.Date;

public class Article extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.meta_title
     *
     * @mbggenerated
     */
    private String metaTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.meta_key
     *
     * @mbggenerated
     */
    private String metaKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.meta_descp
     *
     * @mbggenerated
     */
    private String metaDescp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.src
     *
     * @mbggenerated
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.state
     *
     * @mbggenerated
     */
    private Integer state;

    private String content;

    private String type;

    private String articlContent;

    private String searchType;

    private String notSearchType;

    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.meta_title
     *
     * @return the value of article.meta_title
     * @mbggenerated
     */
    public String getMetaTitle() {
        return metaTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.meta_title
     *
     * @param metaTitle the value for article.meta_title
     * @mbggenerated
     */
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle == null ? null : metaTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.meta_key
     *
     * @return the value of article.meta_key
     * @mbggenerated
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.meta_key
     *
     * @param metaKey the value for article.meta_key
     * @mbggenerated
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey == null ? null : metaKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.meta_descp
     *
     * @return the value of article.meta_descp
     * @mbggenerated
     */
    public String getMetaDescp() {
        return metaDescp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.meta_descp
     *
     * @param metaDescp the value for article.meta_descp
     * @mbggenerated
     */
    public void setMetaDescp(String metaDescp) {
        this.metaDescp = metaDescp == null ? null : metaDescp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.picture
     *
     * @return the value of article.picture
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.picture
     *
     * @param picture the value for article.picture
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.src
     *
     * @return the value of article.src
     * @mbggenerated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.src
     *
     * @param src the value for article.src
     * @mbggenerated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.weight
     *
     * @return the value of article.weight
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.weight
     *
     * @param weight the value for article.weight
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.state
     *
     * @return the value of article.state
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.state
     *
     * @param state the value for article.state
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getArticlContent() {
        return articlContent;
    }

    public void setArticlContent(String articlContent) {
        this.articlContent = articlContent;
    }

    public String getSearchType() {
        return searchType;
    }

    public void setSearchType(String searchType) {
        this.searchType = searchType;
    }

    public String getNotSearchType() {
        return notSearchType;
    }

    public void setNotSearchType(String notSearchType) {
        this.notSearchType = notSearchType;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }
}