package cn.lhzs.data.bean;

import java.util.Date;

public class Product extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_id
     *
     * @mbggenerated
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.banner
     *
     * @mbggenerated
     */
    private String banner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount_price
     *
     * @mbggenerated
     */
    private Double discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount_desc
     *
     * @mbggenerated
     */
    private String discountDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_generalize
     *
     * @mbggenerated
     */
    private String prodGeneralize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.scan_num
     *
     * @mbggenerated
     */
    private Integer scanNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_id
     *
     * @return the value of product.prod_id
     *
     * @mbggenerated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_id
     *
     * @param prodId the value for product.prod_id
     *
     * @mbggenerated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.banner
     *
     * @return the value of product.banner
     *
     * @mbggenerated
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.banner
     *
     * @param banner the value for product.banner
     *
     * @mbggenerated
     */
    public void setBanner(String banner) {
        this.banner = banner == null ? null : banner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount_price
     *
     * @return the value of product.discount_price
     *
     * @mbggenerated
     */
    public Double getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount_price
     *
     * @param discountPrice the value for product.discount_price
     *
     * @mbggenerated
     */
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount_desc
     *
     * @return the value of product.discount_desc
     *
     * @mbggenerated
     */
    public String getDiscountDesc() {
        return discountDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount_desc
     *
     * @param discountDesc the value for product.discount_desc
     *
     * @mbggenerated
     */
    public void setDiscountDesc(String discountDesc) {
        this.discountDesc = discountDesc == null ? null : discountDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.platform
     *
     * @return the value of product.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.platform
     *
     * @param platform the value for product.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_generalize
     *
     * @return the value of product.prod_generalize
     *
     * @mbggenerated
     */
    public String getProdGeneralize() {
        return prodGeneralize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_generalize
     *
     * @param prodGeneralize the value for product.prod_generalize
     *
     * @mbggenerated
     */
    public void setProdGeneralize(String prodGeneralize) {
        this.prodGeneralize = prodGeneralize == null ? null : prodGeneralize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.scan_num
     *
     * @return the value of product.scan_num
     *
     * @mbggenerated
     */
    public Integer getScanNum() {
        return scanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.scan_num
     *
     * @param scanNum the value for product.scan_num
     *
     * @mbggenerated
     */
    public void setScanNum(Integer scanNum) {
        this.scanNum = scanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}