package cn.lhzs.data.bean;

import java.util.Date;

public class Shop extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.web_shop
     *
     * @mbggenerated
     */
    private String webShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.site
     *
     * @mbggenerated
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.sell_name
     *
     * @mbggenerated
     */
    private String sellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.sell_prod
     *
     * @mbggenerated
     */
    private String sellProd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.web_generalize
     *
     * @mbggenerated
     */
    private String webGeneralize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.mobile_url
     *
     * @mbggenerated
     */
    private String mobileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.mobile_generalize
     *
     * @mbggenerated
     */
    private String mobileGeneralize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_addr
     *
     * @mbggenerated
     */
    private String shopAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.banner
     *
     * @mbggenerated
     */
    private String banner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.web_shop
     *
     * @return the value of shop.web_shop
     *
     * @mbggenerated
     */
    public String getWebShop() {
        return webShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.web_shop
     *
     * @param webShop the value for shop.web_shop
     *
     * @mbggenerated
     */
    public void setWebShop(String webShop) {
        this.webShop = webShop == null ? null : webShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.site
     *
     * @return the value of shop.site
     *
     * @mbggenerated
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.site
     *
     * @param site the value for shop.site
     *
     * @mbggenerated
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.type
     *
     * @return the value of shop.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.type
     *
     * @param type the value for shop.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.sell_name
     *
     * @return the value of shop.sell_name
     *
     * @mbggenerated
     */
    public String getSellName() {
        return sellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.sell_name
     *
     * @param sellName the value for shop.sell_name
     *
     * @mbggenerated
     */
    public void setSellName(String sellName) {
        this.sellName = sellName == null ? null : sellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.brand_name
     *
     * @return the value of shop.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.brand_name
     *
     * @param brandName the value for shop.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.sell_prod
     *
     * @return the value of shop.sell_prod
     *
     * @mbggenerated
     */
    public String getSellProd() {
        return sellProd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.sell_prod
     *
     * @param sellProd the value for shop.sell_prod
     *
     * @mbggenerated
     */
    public void setSellProd(String sellProd) {
        this.sellProd = sellProd == null ? null : sellProd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.web_url
     *
     * @return the value of shop.web_url
     *
     * @mbggenerated
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.web_url
     *
     * @param webUrl the value for shop.web_url
     *
     * @mbggenerated
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.web_generalize
     *
     * @return the value of shop.web_generalize
     *
     * @mbggenerated
     */
    public String getWebGeneralize() {
        return webGeneralize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.web_generalize
     *
     * @param webGeneralize the value for shop.web_generalize
     *
     * @mbggenerated
     */
    public void setWebGeneralize(String webGeneralize) {
        this.webGeneralize = webGeneralize == null ? null : webGeneralize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.mobile_url
     *
     * @return the value of shop.mobile_url
     *
     * @mbggenerated
     */
    public String getMobileUrl() {
        return mobileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.mobile_url
     *
     * @param mobileUrl the value for shop.mobile_url
     *
     * @mbggenerated
     */
    public void setMobileUrl(String mobileUrl) {
        this.mobileUrl = mobileUrl == null ? null : mobileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.mobile_generalize
     *
     * @return the value of shop.mobile_generalize
     *
     * @mbggenerated
     */
    public String getMobileGeneralize() {
        return mobileGeneralize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.mobile_generalize
     *
     * @param mobileGeneralize the value for shop.mobile_generalize
     *
     * @mbggenerated
     */
    public void setMobileGeneralize(String mobileGeneralize) {
        this.mobileGeneralize = mobileGeneralize == null ? null : mobileGeneralize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_addr
     *
     * @return the value of shop.shop_addr
     *
     * @mbggenerated
     */
    public String getShopAddr() {
        return shopAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_addr
     *
     * @param shopAddr the value for shop.shop_addr
     *
     * @mbggenerated
     */
    public void setShopAddr(String shopAddr) {
        this.shopAddr = shopAddr == null ? null : shopAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.banner
     *
     * @return the value of shop.banner
     *
     * @mbggenerated
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.banner
     *
     * @param banner the value for shop.banner
     *
     * @mbggenerated
     */
    public void setBanner(String banner) {
        this.banner = banner == null ? null : banner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.creat_time
     *
     * @return the value of shop.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.creat_time
     *
     * @param creatTime the value for shop.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.update_time
     *
     * @return the value of shop.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.update_time
     *
     * @param updateTime the value for shop.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}