package cn.lhzs.data.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "sys_auth")
public class SysAuth extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.aid
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.amid
     *
     * @mbggenerated
     */
    @Column(name = "amid")
    private Long amid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.name
     *
     * @mbggenerated
     */
    @Column(name = "name")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.url
     *
     * @mbggenerated
     */
    @Column(name = "url")
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.state
     *
     * @mbggenerated
     */
    @Column(name = "state")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.create_time
     *
     * @mbggenerated
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.update_time
     *
     * @mbggenerated
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.create_by
     *
     * @mbggenerated
     */
    @Column(name = "create_by")
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.update_by
     *
     * @mbggenerated
     */
    @Column(name = "update_by")
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.aid
     *
     * @return the value of sys_auth.aid
     *
     * @mbggenerated
     */
    public Long getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.aid
     *
     * @param aid the value for sys_auth.aid
     *
     * @mbggenerated
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.amid
     *
     * @return the value of sys_auth.amid
     *
     * @mbggenerated
     */
    public Long getAmid() {
        return amid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.amid
     *
     * @param amid the value for sys_auth.amid
     *
     * @mbggenerated
     */
    public void setAmid(Long amid) {
        this.amid = amid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.name
     *
     * @return the value of sys_auth.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.name
     *
     * @param name the value for sys_auth.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.url
     *
     * @return the value of sys_auth.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.url
     *
     * @param url the value for sys_auth.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.state
     *
     * @return the value of sys_auth.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.state
     *
     * @param state the value for sys_auth.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.create_time
     *
     * @return the value of sys_auth.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.create_time
     *
     * @param createTime the value for sys_auth.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.update_time
     *
     * @return the value of sys_auth.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.update_time
     *
     * @param updateTime the value for sys_auth.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.create_by
     *
     * @return the value of sys_auth.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.create_by
     *
     * @param createBy the value for sys_auth.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth.update_by
     *
     * @return the value of sys_auth.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth.update_by
     *
     * @param updateBy the value for sys_auth.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}