package cn.lhzs.data.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "sys_role_auth")
public class SysRoleAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.raid
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long raid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.rid
     *
     * @mbggenerated
     */
    @Column(name = "rid")
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.aid
     *
     * @mbggenerated
     */
    @Column(name = "aid")
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.state
     *
     * @mbggenerated
     */
    @Column(name = "state")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.create_time
     *
     * @mbggenerated
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.update_time
     *
     * @mbggenerated
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.create_by
     *
     * @mbggenerated
     */
    @Column(name = "create_by")
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.update_by
     *
     * @mbggenerated
     */
    @Column(name = "update_by")
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.raid
     *
     * @return the value of sys_role_auth.raid
     *
     * @mbggenerated
     */
    public Long getRaid() {
        return raid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.raid
     *
     * @param raid the value for sys_role_auth.raid
     *
     * @mbggenerated
     */
    public void setRaid(Long raid) {
        this.raid = raid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.rid
     *
     * @return the value of sys_role_auth.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.rid
     *
     * @param rid the value for sys_role_auth.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.aid
     *
     * @return the value of sys_role_auth.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.aid
     *
     * @param aid the value for sys_role_auth.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.state
     *
     * @return the value of sys_role_auth.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.state
     *
     * @param state the value for sys_role_auth.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.create_time
     *
     * @return the value of sys_role_auth.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.create_time
     *
     * @param createTime the value for sys_role_auth.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.update_time
     *
     * @return the value of sys_role_auth.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.update_time
     *
     * @param updateTime the value for sys_role_auth.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.create_by
     *
     * @return the value of sys_role_auth.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.create_by
     *
     * @param createBy the value for sys_role_auth.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.update_by
     *
     * @return the value of sys_role_auth.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.update_by
     *
     * @param updateBy the value for sys_role_auth.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}