package cn.lhzs.data.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "sys_role_user")
public class SysRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.ruid
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long ruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.uid
     *
     * @mbggenerated
     */
    @Column(name = "uid")
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.rid
     *
     * @mbggenerated
     */
    @Column(name = "rid")
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.state
     *
     * @mbggenerated
     */
    @Column(name = "state")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.create_time
     *
     * @mbggenerated
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.update_time
     *
     * @mbggenerated
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.create_by
     *
     * @mbggenerated
     */
    @Column(name = "create_by")
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.update_by
     *
     * @mbggenerated
     */
    @Column(name = "update_by")
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.ruid
     *
     * @return the value of sys_role_user.ruid
     *
     * @mbggenerated
     */
    public Long getRuid() {
        return ruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.ruid
     *
     * @param ruid the value for sys_role_user.ruid
     *
     * @mbggenerated
     */
    public void setRuid(Long ruid) {
        this.ruid = ruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.uid
     *
     * @return the value of sys_role_user.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.uid
     *
     * @param uid the value for sys_role_user.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.rid
     *
     * @return the value of sys_role_user.rid
     *
     * @mbggenerated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.rid
     *
     * @param rid the value for sys_role_user.rid
     *
     * @mbggenerated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.state
     *
     * @return the value of sys_role_user.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.state
     *
     * @param state the value for sys_role_user.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.create_time
     *
     * @return the value of sys_role_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.create_time
     *
     * @param createTime the value for sys_role_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.update_time
     *
     * @return the value of sys_role_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.update_time
     *
     * @param updateTime the value for sys_role_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.create_by
     *
     * @return the value of sys_role_user.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.create_by
     *
     * @param createBy the value for sys_role_user.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.update_by
     *
     * @return the value of sys_role_user.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.update_by
     *
     * @param updateBy the value for sys_role_user.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}